package com.ps.movie.util

object TestTags {
    const val MOVIE_LIST_TITLE = "MOVIE_LIST_TITLE"
    const val MOVIE_LIST = "MOVIE_LIST"
    const val MOVIE_LIST_ITEM_IMAGE = "MOVIE_LIST_ITEM_IMAGE"
    const val MOVIE_DETAIL_TITLE = "MOVIE_LIST_TITLE"
    const val MOVIE_DETAIL_BACK_BUTTON = "MOVIE_DETAIL_BACK_BUTTON"
    const val MOVIE_DETAIL = "MOVIE_DETAIL"
    const val MOVIE_DETAIL_OVERVIEW = "MOVIE_DETAIL_OVERVIEW"
    const val MOVIE_DETAIL_IMAGE = "MOVIE_DETAIL_IMAGE"
    const val MOVIE_DETAIL_VOTE = "MOVIE_DETAIL_VOTE"
    const val MOVIE_DETAIL_RATING = "MOVIE_DETAIL_RATING"
    const val MOVIE_DETAIL_GENRE = "MOVIE_DETAIL_GENRE"
}
